services:
  # Backend Service (Rust/Axum)
  - type: web
    name: near-treasury-backend
    runtime: rust
    plan: starter
    rootDir: nt-be
    buildCommand: unset DATABASE_URL && cargo build --release --bin nt-be
    startCommand: ./target/release/nt-be
    domains:
      - api.trezu.app
    envVars:
      - key: FASTNEAR_API_KEY
        sync: false
      - key: SIGNER_KEY
        sync: false
      - key: SIGNER_ID
        sync: false
      - key: SPUTNIK_DAO_API_BASE
        sync: false
      - key: RUST_LOG
        value: info
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
    healthCheckPath: /api/health

  # Frontend Service (Next.js)
  - type: web
    name: near-treasury-frontend
    runtime: node
    plan: starter
    rootDir: nt-fe
    buildCommand: bun install && node ./node_modules/geoip-lite/scripts/updatedb.js license_key=$MAXMIND_LICENSE_KEY && bun run build && cp -r public .next/standalone/ && cp -r .next/static .next/standalone/.next/
    startCommand: node .next/standalone/server.js
    domains:
      - trezu.app
      - www.trezu.app
    envVars:
      - key: NODE_ENV
        value: production
      - key: MAXMIND_LICENSE_KEY
        sync: false
      - key: NEXT_PUBLIC_BACKEND_API_BASE
        value: https://api.trezu.app
    healthCheckPath: /

  - type: web
    name: nt-nocodb
    runtime: image
    plan: starter
    image:
      url: docker.io/nocodb/nocodb:0.301.2
    disk: 
      name: nocodb-disk
      mountPath: /usr/app/data/
      sizeGB: 1
    domains:
      - nocodb.trezu.app
      - www.nocodb.trezu.app
    envVars:
      - key: NC_CONNECTION_ENCRYPT_KEY
        generateValue: true
      - key: NC_AUTH_JWT_SECRET
        generateValue: true
      - key: NC_GOOGLE_CLIENT_ID
        sync: false
      - key: NC_GOOGLE_CLIENT_SECRET
        sync: false
      - key: NC_PUBLIC_URL
        sync: false
    healthCheckPath: /

databases:
  - name: database
    plan: basic-1gb
    diskSizeGB: 1
    ipAllowList: [] # No entries in the IP allow list
